### ISSUE TITLE
There is no output for producing the haProxy version

### ISSUE THREAD

**Issue by tangi07** [websoft9dev/role_haproxy#8]
![image](https://user-images.githubusercontent.com/92657958/156125484-5218d063-4406-4414-a184-3afa1c00238b.png)
解决方法：haproxy -v | grep "version" | awk -F "  "  '{print $1}'
![image](https://user-images.githubusercontent.com/92657958/156129372-c2e1e2f7-8781-4097-9b3f-4709e5cfd028.png)

**Comment by qiaofeng1227** [comment]
Ha-proxy version: 1.8.26
